defaults:
  - _self_
  - encoder: identity
  - action_ae: discretizers/k_means_kitchen_best
  - env: relay_kitchen_traj
  - state_prior: mingpt_kitchen_best
  - env_vars: env_vars

lazy_init_models: True

# Dataset details
train_fraction: 0.95
batch_size: 64
num_workers: 32
window_size: 10

# Training details
num_training_epochs: 10
data_parallel: False
device: cuda
optim: Adam
save_latents: False

lr: 1e-4
weight_decay: 0.1
betas:
  - 0.9
  - 0.95
grad_norm_clip: 1.0
seed: 42

# Prior training details
num_prior_epochs: 50
eval_prior_every: 1
save_prior_every: 1

# Logging frequency
eval_every: -1
save_every: 1

# Wandb config
project: vil # behavior_transformer_repro_test
experiment: kitchen_train

log_wandb: False
min_h5_dataset:
  dirname:  "/checkpoint/mandizhao/train_seeds/"
  template: "*/*/*/*.h5"
  verbose: False
  context_keys: [obj_goal] #[new_left, new_right] # ['r3m:new_top'] # old schema: ['rgb:left_cam:240x424:flat']
  input_keys: [observations] #[new_left, new_right] # ['r3m:new_left', 'r3m:new_right'] # old: ['rgb:left_cam:240x424:flat']
  proprio_keys: ['robot_jnt', 'robot_vel']
  context_window: 10
  np_seed: 1
  img_size: [224,224]
  split_ratio: 0.99
  num_load_trials: -1
  use_compressed: False
  crop: False
  random_crop: False
  jitter: False
  cutoff: 0


hydra:
  job:
    override_dirname: ${experiment}
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${experiment}
    subdir: ${hydra.job.num}
